name: build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev

      # build project
      - name: mkdir
        run: mkdir build
      - name: cmake build
        run: cmake -Bbuild -H.
      - name: cmake make
        run: cmake --build build/ --target all
        env:
          MAKEFLAGS: "-j2"
      # run tests
      - name: run tests
        run: cd tests && ../build/bitcointest